### ISSUE TITLE
Info Windows support

### ISSUE THREAD

**Issue by ImpossivelPT** [FelipeBohnertPaetzold/v-maps#4]
Do you have any plans on adding Info Windows to show marker info for example?

Thanks for the great component!

**Comment by FelipeBohnertPaetzold** [comment]
Hi,
at first the component only shows markers on the map, but this is a possibility, thanks for the suggestion.

**Comment by FelipeBohnertPaetzold** [comment]
Hey @ImpossivelPT , 
I implemented the functionality you suggested, it's available in v1.0.2, the usage instructions are in README.md, but just pass the string via prop to the `v-marker`

Thanks for the suggestion.

**Comment by ImpossivelPT** [comment]
Thanks a lot! I think this is a great addition to the component.
